### PR TITLE
[ENH] Functioning Dockerfile

### PR DESCRIPTION
**Pull request by jdkent**
Fixes # None

Changes proposed in this pull request
- add working Dockerfile
- add tests on data for circleci
- small edits to codebase

### CODE REVIEW

**Comment by jdkent** [comment]
This is ready for review!

 In the future, if the circleci tests do not pass, do not merge the pull request, travis I suspect will continue to fail for a while.

I encourage you to add tests that are relevant to your use cases. 

You can use the current test as a model.

**Comment by tbweng** [comment]
Thanks @jdkent for containerizing and adding unit testing!

One thing off the top of my head to consider: octave does not implement parfor loops the way it is expected to run in Matlab (e.g., in firstlevelseeding_parallel.m). I remember looking into this, and octave can interpret <parfor>, but it will just run it as a normal for loop. Octave has its own parallel package (https://wiki.octave.org/Parallel_package), but its syntax is different than Matlab's .

**Comment by jdkent** [comment]
Good comment to note @tbweng!

I currently consider that out of the scope for this pull request, but once this is merged, it would be great to have an issue opened talking about that.

In addition to your solution, we could also try to incorporate the compiled matlab runtime environments into the docker container. (I am trying to avoid matlab, so I haven't learned how to do this)

tbh, I'm treating this code like a hot potato, the sooner I can pass it off for someone else to work on, the better. I just want it to be minimally reproducible and have at least one test so we never lose basic functionality.

There are certain design constraints (I'm kicking myself for using clobber so now I can't set the bash script to exit at the first sign of an error), that can make this code difficult to debug.

**Comment by mwvoss** [comment]
When running the test command through docker, freesurfer is not found in the docker container:

```
bash-3.2$ docker run -it \
> -v /Volumes/vosslabhpc/Projects/CREST:/data \
> hbclab/restingstate \
>   --epi=/data/sub-AMBI003/func/sub-AMBI003_task-rest_bold.nii.gz \
>   --t1=/data/derivatives/fmriprep/sub-AMBI003/anat/sub-AMBI003_desc-preproc_T1w.nii.gz \
>   --t1_mask=/data/derivatives/fmriprep/sub-AMBI003/anat/sub-AMBI003_desc-brain_mask.nii.gz \
>   --roiList=/data/derivatives/rois/roi_list.txt \
>   --compcor

no sesID
native orientation = RPI
No need to reorient.  Dataset already in RPI orientation.
native orientation = RPI
No need to reorient.  Dataset already in RPI orientation.
freesurfer is either not downloaded or not defined in your path, exiting script
```

**Comment by jdkent** [comment]
@mwvoss 

I gave you the container `jdkent/restingstate` you are using `hbclab/restingstate`, that should explain the error you are getting.

**Pull request merged**
